repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: debug-statements
      - id: check-ast
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args: [--config-file=nexus_core/pyproject.toml, --ignore-missing-imports, --explicit-package-bases]
        language: system
        types: [python]
        files: ^nexus_core/

  - repo: https://github.com/returntocorp/semgrep
    rev: 'v1.65.0'
    hooks:
      - id: semgrep
        args: ['--config', auto, '--error']
        stages: [pre-push]

  - repo: local
    hooks:
      - id: docker-test
        name: docker-test
        entry: bash -c "docker build -t nexus-seeker-test -f Dockerfile.test . && docker run --rm nexus-seeker-test python -m pytest tests"
        language: system
        stages: [pre-commit]
        always_run: true
        pass_filenames: false
