services:
  nexus-seeker:
    build: .
    container_name: nexus-seeker-discord-bot
    restart: unless-stopped
    stop_grace_period: 1m
    env_file:
      - .env
    volumes:
      - nexus_data:/app/data
    environment:
      - TZ=America/New_York
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  nexus_data:
